13 fail testu

diff --git a/dirgraph b/dirgraph
--- a/dirgraph
+++ b/dirgraph
@@ -17,7 +17,7 @@ N=0
 # --- Processing flags ---
 while getopts :i:n o
 do	case "$o" in
-		i) FILE_ERE="$OPTARG";;
+		i) FILE_ERE="${-not -regex $OPTARG}";;
 		n) N=1;;
 		*) HELP=1;;
 	esac
@@ -27,12 +27,11 @@ done
 # --- Processing target directory ---
 ARGC=$#
 if [ "$OPTIND" -eq "$ARGC" ]; then
-	((OPTIND--))
-	shift $OPTIND	
+	shift $(($OPTIND - 1))	
 	DIR="$*"
 else
 	((OPTIND--))
-	if [ "$OPTIND" -eq "$ARGC" ]; then
+	if [ $(($OPTIND - 1)) -eq "$ARGC" ]; then
 		DIR=$(pwd)
 	else
 		HELP=1
@@ -42,8 +41,16 @@ fi
 
 # --- Returning help ---
 if [ "$HELP" -eq 1 ]; then
-	echo "NAPOVEDA"
-	exit 0
+	echo "This script creates report of directory" >&2
+	echo "Syntax: dirgraph [-i FILE_ERE] [-n] [DIR]" >&2
+	exit 1 # jedna nebo nula?
+fi
+
+
+# --- Check for errors ---
+if [ ! -d "$DIR" ]; then
+	echo "Error: Directory doesn't exist" >&2
+	exit 1
 fi
 
 
@@ -57,45 +64,50 @@ if [ "$N" -eq 1 ]; then
 fi
 
 
+# --- Ignoring regex (-i FLAG) ---
+
+
+
 # --- Printing head of result ---
 echo "Root directory: $DIR"
 printf "Directories: %d\n" $(find $DIR -type d | wc -l)
 
 
-# --- File size histogram ---
-find $DIR -type f -not -regex "$FILE_ERE"  -exec du -b {} + | awk -v gmax="$N" '
+# --- File size histogram --- -iname "$FILE_ERE", mozna jestli du nepotrebuje -b na merlinovi
+find "$DIR" -type f $FILE_ERE -exec wc -c {} + | awk -v gmax="$N" '
 {
-	if($1 < 100)
-		size[0]++;
-	else if($1 < 1024)
-		size[1]++;
-	else if($1 < 10240)
-		size[2]++;
-	else if($1 < 102400)
-		size[3]++;
-	else if($1 < 1048576)
-		size[4]++;
-	else if($1 < 10485760)
-		size[5]++;
-	else if($1 < 104857600)
-		size[6]++;
-	else if($1 < 1073741824)
-		size[7]++;
-	else
-		size[8]++;
+	if($2 != "total")
+		if($1 < 100)
+			size[0]++;
+		else if($1 < 1024)
+			size[1]++;
+		else if($1 < 10240)
+			size[2]++;
+		else if($1 < 102400)
+			size[3]++;
+		else if($1 < 1048576)
+			size[4]++;
+		else if($1 < 10485760)
+			size[5]++;
+		else if($1 < 104857600)
+			size[6]++;
+		else if($1 < 1073741824)
+			size[7]++;
+		else
+			size[8]++;
 }
 END{
-	print "All files: "NR;
+	print "All files: "NR-1;
 
 	prefix[0] = "<100 B";
 	prefix[1] = "<1 KiB";
 	prefix[2] = "<10 KiB";
 	prefix[3] = "<100 KiB";
 	prefix[4] = "<1 MiB";
-	prefix[5] = "<10 Mib";
-	prefix[6] = "<100 Mib";
+	prefix[5] = "<10 MiB";
+	prefix[6] = "<100 MiB";
 	prefix[7] = "<1 GiB";
-	prefix[8] = ">= 1 GiB";
+	prefix[8] = ">=1 GiB";
 
 	if(gmax != 0)
 		gmax -= 13; # Asi osetrit
@@ -119,7 +131,7 @@ END{
 }'
 
 # --- File type histogram ---
-find $DIR -type f -not -regex "$FILE_ERE" -exec file -b {} \; | cut -c -40 | sort | uniq -c | sort -n -r | awk -v gmax="$N" '
+find "$DIR" -type f $FILE_ERE -exec file -b {} \; | cut -c -40 | sort | uniq -c | sort -n -r | awk -v gmax="$N" '
 BEGIN{
 	if(gmax != 0)
 		gmax -= 48;
@@ -145,3 +157,5 @@ BEGIN{
 	}
 	printf "\n";
 }'
+
+exit 0
